all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod:
  hosts:
    client:
      ansible_host: 192.168.1.29

  vars:
    ansible_password: xv!54P94
    env: production
